// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdntyounxyewkkwtkuyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkbnR5b3VueHlld2trd3RrdXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzYwMTEsImV4cCI6MjA2NDkxMjAxMX0.-fdFApy_tSJeTU3Sw9V-F6XwRAm9Vij7CjoUMtqG0cI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);